export const POLL_CREATING = 'POLL_CREATING';
export const POLL_CREATE_SUCCESS = 'POLL_CREATE_SUCCESS';
export const POLL_CREATE_ERROR = 'POLL_CREATE_ERROR';
export const POLL_CREATE_RESET = 'POLL_CREATE_RESET';
