export const USER_POLLS_GETTING = "USER_POLLS_GETTING";
export const USER_POLLS_GETTING_SUCCESS = "USER_POLLS_GETTING_SUCCESS";
export const USER_POLLS_GETTING_ERROR = "USER_POLLS_GETTING_ERROR";
export const USER_POLL_DELETING = "USER_POLL_DELETING";
export const USER_POLL_DELETING_SUCCESS = "USER_POLL_DELETING_SUCCESS";
export const USER_POLL_DELETING_ERROR = "USER_POLL_DELETING_ERROR";
