export const POLL_GETTING = "POLL_GETTING";
export const POLL_GETTING_SUCCESS = "POLL_GETTING_SUCCESS";
export const POLL_GETTING_ERROR = "POLL_GETTING_ERROR";
export const POLL_UPDATING = "POLL_UPDATING";
export const POLL_UPDATING_SUCCESS = "POLL_UPDATING_SUCCESS";
export const POLL_UPDATING_ERROR = "POLL_UPDATING_ERROR";
